package agents;

public enum AgentActionSettler {
	PLACE_FIRST_TURN_STREET,
	PLACE_FIRST_TURN_TOWN,
	PLACE_STREET,
	PLACE_TOWN,
	PLACE_CITY,
	PASS_TURN,
	ADVANCE_TURN,
	ROLL_DIE,
	CHANGE_THIEVES,
	DISCARD_RESSOURCES,
	STEAL_RESSOURCES,
	BUY_CARD,
	ACTIVATE_CARD,
	TRADE_WITH_BANK,
	TRADE_WITH_PLAYER,
	TRADE_WITH_HUMAN,
	TRADE_HUMAN_DENIED,
	TRADE_HUMAN_ACCEPTED
}
